// <auto-generated />
using BomApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BomApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BomDbContext))]
    [Migration("20260528000000_AddWarehouseShelfToBomProductionDetails")]
    partial class AddWarehouseShelfToBomProductionDetails
    {
    }
}
