// <auto-generated />
using System;
using BomApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BomApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BomDbContext))]
    [Migration("20260424061924_MoveToPublicSchema")]
    partial class MoveToPublicSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BomApp.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_changed_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("bom_audit_logs", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.Bom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<decimal>("YieldQuantity")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("yield_quantity");

                    b.Property<string>("YieldUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("yield_unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_boms_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_boms_status");

                    b.ToTable("bom_boms", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.BomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("BomId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_id");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.HasKey("Id");

                    b.HasIndex("BomId")
                        .HasDatabaseName("idx_bom_assignments_bom_id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("idx_bom_assignments_item_code");

                    b.ToTable("bom_assignments", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.BomLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BomId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_id");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_code");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("material_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("SubBomId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_bom_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("BomId")
                        .HasDatabaseName("idx_bom_lines_bom_id");

                    b.HasIndex("SubBomId");

                    b.ToTable("bom_lines", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BomId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_id");

                    b.Property<string>("BomSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bom_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedVia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("UI")
                        .HasColumnName("created_via");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_no");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly?>("SourceDocDateFrom")
                        .HasColumnType("date")
                        .HasColumnName("source_doc_date_from");

                    b.Property<DateOnly?>("SourceDocDateTo")
                        .HasColumnType("date")
                        .HasColumnName("source_doc_date_to");

                    b.PrimitiveCollection<string[]>("SourceSoNumbers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("source_so_numbers");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_production_orders_created_at");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("idx_production_orders_item_code");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("SourceSoNumbers")
                        .HasDatabaseName("idx_production_orders_source_so");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SourceSoNumbers"), "gin");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_production_orders_status");

                    b.ToTable("bom_production_orders", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.ProductionOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_code");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("material_name");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<decimal>("RequiredQuantity")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("required_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("idx_po_lines_production_order_id");

                    b.ToTable("bom_production_order_lines", "public");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.BomAssignment", b =>
                {
                    b.HasOne("BomApp.Domain.Entities.Bom", "Bom")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.BomLine", b =>
                {
                    b.HasOne("BomApp.Domain.Entities.Bom", "Bom")
                        .WithMany("Lines")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomApp.Domain.Entities.Bom", "SubBom")
                        .WithMany()
                        .HasForeignKey("SubBomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bom");

                    b.Navigation("SubBom");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("BomApp.Domain.Entities.Bom", "Bom")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.ProductionOrderLine", b =>
                {
                    b.HasOne("BomApp.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.Bom", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BomApp.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
